import { Hotel } from "./useHotels.types";

export const HOTELS_DATA: Hotel[] = [
  {
    id: 1,
    name: "Serenity Grand Hotel",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "123 Tranquil Avenue, Blissful City",
    price: 200,
    quantityStar: 4,
    mark: 4.5,
    quantityReviews: 120,
  },
  {
    id: 2,
    name: "Azure Horizon Resort",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "456 Ocean View Street, Coastal Paradise",
    price: 150,
    quantityStar: 5,
    mark: 4.2,
    quantityReviews: 80,
  },
  {
    id: 3,
    name: "Royal Oasis Retreat",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "789 Majesty Lane, Regal Town",
    price: 300,
    quantityStar: 5,
    mark: 4.9,
    quantityReviews: 200,
  },
  {
    id: 4,
    name: "Ethereal Springs Lodge",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "101 Enchanted Trail, Mystical Valley",
    price: 180,
    quantityStar: 4,
    mark: 4.4,
    quantityReviews: 100,
  },
  {
    id: 5,
    name: "Tranquility Heights Inn",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "234 Peaceful Boulevard, Calmville",
    price: 250,
    quantityStar: 5,
    mark: 4.8,
    quantityReviews: 150,
  },
  {
    id: 6,
    name: "Celestial View Hotel",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "567 Heavenly Drive, Serene Village",
    price: 220,
    quantityStar: 4,
    mark: 4.6,
    quantityReviews: 130,
  },
  {
    id: 7,
    name: "Majestic Pines Resort",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "890 Grand Forest Road, Majestic Woods",
    price: 280,
    quantityStar: 5,
    mark: 4.7,
    quantityReviews: 180,
  },
  {
    id: 8,
    name: "Harmony Haven Retreat",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "112 Blissful Circle, Harmony Town",
    price: 190,
    quantityStar: 3,
    mark: 4.1,
    quantityReviews: 90,
  },
  {
    id: 9,
    name: "Crimson Sunset Hotel",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "345 Twilight Lane, Sunset Harbor",
    price: 210,
    quantityStar: 4,
    mark: 4.3,
    quantityReviews: 110,
  },
  {
    id: 10,
    name: "Golden Glade Lodge",
    imageUrl: "/assets/img/cards/paris.jpeg",
    address: "678 Tranquil Trail, Golden Valley",
    price: 270,
    quantityStar: 5,
    mark: 4.9,
    quantityReviews: 220,
  }
];